name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *'  # 每天运行一次
  workflow_dispatch:  # 手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v2
        with:
          repository: cmliu/CF-Workers-docker.io
          token: ${{ secrets.GITHUB_TOKEN }}
          path: source

      - name: Checkout fork repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: fork

      - name: Sync changes
        run: |
          cd fork
          git remote add upstream ../source
          git fetch upstream
          git checkout main
          git merge upstream/main
          git push origin main
